# Generated by Django 2.2.2 on 2020-09-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('text', models.TextField()),
                ('audioFile', models.FileField(null=True, upload_to='audio/')),
            ],
        ),
    ]
