# Generated by Django 2.2.2 on 2020-09-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechdata',
            name='audioFile',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
