# Generated by Django 2.2.2 on 2020-09-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0002_auto_20200916_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechdata',
            name='lang',
            field=models.CharField(default='hi', max_length=100),
        ),
    ]
