# Generated by Django 2.2.2 on 2020-09-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0003_speechdata_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechdata',
            name='lang',
            field=models.CharField(max_length=100),
        ),
    ]
