# Generated by Django 2.2.2 on 2020-09-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0005_auto_20200917_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechdata',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speechdata',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
