# Generated by Django 2.2.2 on 2020-09-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0006_auto_20200917_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechdata',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='speechdata',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
